# Generated by Django 4.2.16 on 2024-11-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('archivo', 'Archivo'), ('popular', 'Popular'), ('nuevo', 'Nuevo Drop')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
