# Generated by Django 4.2.16 on 2024-12-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_categoria_alter_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='colores_disponibles',
            field=models.CharField(default=1, help_text='Colores separados por comas (Ej: Rojo,Azul,Negro)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tallas_disponibles',
            field=models.CharField(default=12, help_text='Tallas separadas por comas (Ej: S,M,L,XL)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
