# Generated by Django 4.2.16 on 2025-01-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_producto_categoria_itemcarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colores_disponibles',
            field=models.CharField(blank=True, help_text='Colores separados por comas (Ej: Rojo,Azul,Negro)', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tallas_disponibles',
            field=models.CharField(blank=True, help_text='Tallas separadas por comas (Ej: S,M,L,XL)', max_length=255),
        ),
    ]
