# Generated by Django 4.2.6 on 2025-01-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_order_total_price_carrito_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen_principal',
            new_name='imagen',
        ),
    ]
