# Generated by Django 4.2.6 on 2025-06-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_order_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug_imagen',
            field=models.SlugField(blank=True, help_text='Ejemplo: max_overweight_oversized', max_length=255),
        ),
    ]
