# Generated by Django 4.2.6 on 2026-04-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_skydrop_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colores_disponibles',
            field=models.CharField(help_text='negro, blanco, guinda, azul, offwhite, slate_blue, latte', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug_imagen',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tallas_disponibles',
            field=models.CharField(max_length=100),
        ),
    ]
