# Generated by Django 4.2.16 on 2026-05-09 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0027_cashregisterclosure'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('ultimos_4', models.CharField(blank=True, max_length=4, null=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dia_corte', models.PositiveSmallIntegerField(default=1)),
                ('dia_pago', models.PositiveSmallIntegerField(default=20)),
                ('activa', models.BooleanField(default=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarjeta de crédito',
                'verbose_name_plural': 'Tarjetas de crédito',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ejemplo: Mayo 2026', max_length=80)),
                ('fecha_corte', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('saldo_corte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_pagado', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('other', 'Otro')], default='transfer', max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='tienda.creditcardaccount')),
            ],
            options={
                'verbose_name': 'Estado de cuenta de tarjeta',
                'verbose_name_plural': 'Estados de cuenta de tarjetas',
                'ordering': ['fecha_vencimiento', 'estado', 'id'],
            },
        ),
    ]
