# Generated by Django 4.2.16 on 2026-05-09 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0028_creditcardaccount_creditcardstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('asset', 'Activo'), ('liability', 'Pasivo'), ('equity', 'Capital'), ('income', 'Ingreso'), ('cost', 'Costo'), ('expense', 'Gasto')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tienda.accountingaccount')),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Catálogo de cuentas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso'), ('diary', 'Diario')], default='diary', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('pos', 'Punto de venta'), ('expense', 'Gasto'), ('credit_card', 'Tarjeta de credito'), ('inventory', 'Inventario')], default='manual', max_length=20)),
                ('concept', models.CharField(max_length=180)),
                ('reference', models.CharField(blank=True, max_length=80, null=True)),
                ('is_posted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credit_card_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='tienda.creditcardstatement')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='tienda.expense')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='tienda.order')),
            ],
            options={
                'verbose_name': 'Póliza contable',
                'verbose_name_plural': 'Pólizas contables',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=180)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='tienda.accountingaccount')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tienda.journalentry')),
            ],
            options={
                'verbose_name': 'Partida de póliza',
                'verbose_name_plural': 'Partidas de póliza',
                'ordering': ['id'],
            },
        ),
    ]
