# Generated by Django 4.2.16 on 2026-05-10 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0031_seed_shipping_income_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriodClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start', models.DateField(unique=True)),
                ('month_end', models.DateField()),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unbalanced_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre contable',
                'verbose_name_plural': 'Cierres contables',
                'ordering': ['-month_start'],
            },
        ),
    ]
