# Generated by Django 4.2.16 on 2026-05-10 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0032_accountingperiodclose'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('cash', 'Efectivo'), ('bank', 'Banco'), ('processor', 'Procesador de pago'), ('other', 'Otro')], default='bank', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_accounts', to='tienda.accountingaccount')),
            ],
            options={
                'verbose_name': 'Cuenta de dinero',
                'verbose_name_plural': 'Cuentas de dinero',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=180)),
                ('movement_type', models.CharField(choices=[('deposit', 'Depósito'), ('withdrawal', 'Retiro'), ('payment', 'Pago'), ('fee', 'Comisión'), ('transfer', 'Transferencia'), ('other', 'Otro')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_movements', to='tienda.journalentry')),
                ('money_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_movements', to='tienda.moneyaccount')),
            ],
            options={
                'verbose_name': 'Movimiento bancario',
                'verbose_name_plural': 'Movimientos bancarios',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
