# Generated by Django 4.2.16 on 2026-05-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0035_resena_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
