# Generated by Django 4.2.16 on 2026-05-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0036_delete_itemcarrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='popup', help_text='popup | footer | etc.', max_length=40)),
                ('coupon_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Suscriptor de newsletter',
                'verbose_name_plural': 'Suscriptores de newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
