# Generated by Django 4.2.16 on 2026-06-04 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0037_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje (%)'), ('fixed', 'Monto fijo ($)'), ('free_shipping', 'Envío gratis')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Compra mínima para aplicar', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Vacío = ilimitado', null=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código de descuento',
                'verbose_name_plural': 'Códigos de descuento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productos/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Menor = aparece primero')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Galería de imágenes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('defective', 'Defectuoso / dañado'), ('wrong_size', 'Talla incorrecta'), ('wrong_item', 'Artículo incorrecto'), ('not_as_described', 'No era como se describía'), ('changed_mind', 'Cambio de opinión'), ('other', 'Otro')], max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('approved', 'Aprobada'), ('received', 'Recibida en bodega'), ('restocked', 'Reingresada a inventario'), ('refunded', 'Reembolsada'), ('rejected', 'Rechazada')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('restock', models.BooleanField(default=True, help_text='Reingresar al inventario al aprobar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='tienda.order')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tienda.promocode'),
        ),
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10)),
                ('pecho', models.DecimalField(blank=True, decimal_places=1, help_text='cm', max_digits=5, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=1, help_text='cm', max_digits=5, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=1, help_text='cm', max_digits=5, null=True)),
                ('hombro', models.DecimalField(blank=True, decimal_places=1, help_text='cm', max_digits=5, null=True)),
                ('manga', models.DecimalField(blank=True, decimal_places=1, help_text='cm (opcional)', max_digits=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_chart', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Medida de talla',
                'verbose_name_plural': 'Tabla de tallas',
                'ordering': ['product'],
                'unique_together': {('product', 'talla')},
            },
        ),
    ]
