# Generated by Django 4.2.16 on 2026-09-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0038_promo_gallery_returns_sizechart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo del producto en el momento de la venta. Se congela aquí para que la utilidad de un mes ya cerrado no cambie cuando recibas mercancía a otro costo.', max_digits=10, null=True, verbose_name='Costo unitario'),
        ),
    ]
