# Generated by Django 4.2.16 on 2026-05-19 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLibreCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('nickname', models.CharField(blank=True, max_length=120)),
                ('site_id', models.CharField(default='MLM', help_text='MLM=México, MLA=Argentina, etc.', max_length=10)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Credenciales',
            },
        ),
        migrations.CreateModel(
            name='MercadoLibreListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_id', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency_id', models.CharField(default='MXN', max_length=10)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('permalink', models.URLField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('listing_type_id', models.CharField(blank=True, max_length=40)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='MercadoLibreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_id', models.BigIntegerField(unique=True)),
                ('status', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField()),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency_id', models.CharField(default='MXN', max_length=10)),
                ('buyer_nickname', models.CharField(blank=True, max_length=120)),
                ('buyer_id', models.BigIntegerField(blank=True, null=True)),
                ('shipping_status', models.CharField(blank=True, max_length=40)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido ML',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='MercadoLibreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mercadolibre.mercadolibreorder')),
            ],
            options={
                'verbose_name': 'Producto del pedido',
                'verbose_name_plural': 'Productos del pedido',
            },
        ),
    ]
