# Generated by Django 4.2.16 on 2026-05-19 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0037_newslettersubscriber'),
        ('mercadolibre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolibrelisting',
            name='last_pushed_stock',
            field=models.PositiveIntegerField(blank=True, help_text='Último stock que enviamos a ML; evita loops de sync', null=True),
        ),
        migrations.AddField(
            model_name='mercadolibrelisting',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto local enlazado para sync de inventario bidireccional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_listings', to='tienda.producto'),
        ),
    ]
