# Generated by Django 4.2.16 on 2026-05-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0002_mercadolibrelisting_last_pushed_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolibreorder',
            name='pushed_tracking_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo enviamos los datos de tracking a ML por última vez', null=True),
        ),
        migrations.AddField(
            model_name='mercadolibreorder',
            name='shipping_id',
            field=models.BigIntegerField(blank=True, help_text='ID del envío en Mercado Envíos', null=True),
        ),
        migrations.AddField(
            model_name='mercadolibreorder',
            name='tracking_carrier',
            field=models.CharField(blank=True, help_text='Nombre de la paquetería (DHL, Estafeta, etc.)', max_length=40),
        ),
        migrations.AddField(
            model_name='mercadolibreorder',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Número de guía cuando se envía con paquetería propia', max_length=80),
        ),
    ]
