# Generated by Django 4.2.16 on 2026-05-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0003_mercadolibreorder_pushed_tracking_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolibreorder',
            name='marketplace_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión cobrada por Mercado Libre por la venta', max_digits=12),
        ),
        migrations.AddField(
            model_name='mercadolibreorder',
            name='net_received_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dinero neto recibido por el vendedor (después de fees y envío)', max_digits=12),
        ),
        migrations.AddField(
            model_name='mercadolibreorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de envío (cuando lo cubre el vendedor)', max_digits=12),
        ),
        migrations.AddField(
            model_name='mercadolibreorder',
            name='stock_decremented',
            field=models.BooleanField(default=False, help_text='True si ya descontamos stock local por este pedido. Sirve para revertir si después se cancela.'),
        ),
    ]
