from .base import *
from decouple import config

DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# --- Claves de pago y servicios externos ---
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
META_PIXEL_ID = config('META_PIXEL_ID', default='')
META_PIXEL_ACCESS_TOKEN = config('META_PIXEL_ACCESS_TOKEN', default='')
META_PIXEL_TEST_EVENT_CODE = config('META_PIXEL_TEST_EVENT_CODE', default='')
FACEBOOK_DOMAIN_VERIFICATION = config('FACEBOOK_DOMAIN_VERIFICATION', default='')
GA4_MEASUREMENT_ID = config('GA4_MEASUREMENT_ID', default='')
GOOGLE_SITE_VERIFICATION = config('GOOGLE_SITE_VERIFICATION', default='')
GOOGLE_MERCHANT_VERIFICATION = config('GOOGLE_MERCHANT_VERIFICATION', default='')

# --- Skydrop ---
SKYDROP_CLIENT_ID = config('SKYDROP_CLIENT_ID', default='')
SKYDROP_CLIENT_SECRET = config('SKYDROP_CLIENT_SECRET', default='')
SKYDROP_API_BASE_URL = config('SKYDROP_API_BASE_URL', default='https://pro.skydropx.com')
SKYDROP_WEBHOOK_SECRET = config('SKYDROP_WEBHOOK_SECRET', default='')
SKYDROP_PRINTING_FORMAT = config('SKYDROP_PRINTING_FORMAT', default='standard')
SKYDROP_DEFAULT_PHONE = config('SKYDROP_DEFAULT_PHONE', default='')
SKYDROP_DEFAULT_EMAIL = config('SKYDROP_DEFAULT_EMAIL', default='')
SKYDROP_DEFAULT_PARCEL_WEIGHT = config('SKYDROP_DEFAULT_PARCEL_WEIGHT', default=0.8, cast=float)
SKYDROP_DEFAULT_PARCEL_LENGTH = config('SKYDROP_DEFAULT_PARCEL_LENGTH', default=35, cast=int)
SKYDROP_DEFAULT_PARCEL_WIDTH = config('SKYDROP_DEFAULT_PARCEL_WIDTH', default=28, cast=int)
SKYDROP_DEFAULT_PARCEL_HEIGHT = config('SKYDROP_DEFAULT_PARCEL_HEIGHT', default=6, cast=int)
SKYDROP_DISTANCE_UNIT = config('SKYDROP_DISTANCE_UNIT', default='CM')
SKYDROP_MASS_UNIT = config('SKYDROP_MASS_UNIT', default='KG')
SKYDROP_ORIGIN_NAME = config('SKYDROP_ORIGIN_NAME', default='Cult Classics')
SKYDROP_ORIGIN_COMPANY = config('SKYDROP_ORIGIN_COMPANY', default='Cult Classics')
SKYDROP_ORIGIN_PHONE = config('SKYDROP_ORIGIN_PHONE', default='')
SKYDROP_ORIGIN_EMAIL = config('SKYDROP_ORIGIN_EMAIL', default='')
SKYDROP_ORIGIN_STREET1 = config('SKYDROP_ORIGIN_STREET1', default='')
SKYDROP_ORIGIN_STREET2 = config('SKYDROP_ORIGIN_STREET2', default='')
SKYDROP_ORIGIN_REFERENCE = config('SKYDROP_ORIGIN_REFERENCE', default='')
SKYDROP_ORIGIN_POSTAL_CODE = config('SKYDROP_ORIGIN_POSTAL_CODE', default='')
SKYDROP_ORIGIN_STATE = config('SKYDROP_ORIGIN_STATE', default='')
SKYDROP_ORIGIN_CITY = config('SKYDROP_ORIGIN_CITY', default='')
SKYDROP_ORIGIN_NEIGHBORHOOD = config('SKYDROP_ORIGIN_NEIGHBORHOOD', default='')
SKYDROP_ORIGIN_COUNTRY_CODE = config('SKYDROP_ORIGIN_COUNTRY_CODE', default='MX')

# --- Archivos estáticos y media ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'
STATIC_ROOT = BASE_DIR.parent / 'staticfiles'

# --- Email (consola en local) ---
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
